libvpd: Remove build warnings
The following build warnings were removed.

src/common.c: In function 'concat_list':
src/common.c:62:13: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
  head->next = addme;
             ^
src/vpddbenv_c.c: In function 'fetch_system':
src/vpddbenv_c.c:136:3: warning: passing argument 1 of 'unpack_system' discards 'const' qualifier from pointer target type [enabled by default]
   ret = unpack_system( sqlite3_column_blob( pstmt, 0 ) );
   ^
In file included from ./src/libvpd-2/vpddbenv.h:32:0,
                 from src/vpddbenv_c.c:24:
./src/libvpd-2/system.h:67:17: note: expected 'void *' but argument is of type 'const void *'
 struct system * unpack_system( void * buffer );
                 ^
src/component_c.c: In function 'add_component':
src/component_c.c:593:13: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
  head->next = addme;
             ^
src/dataitem_c.c: In function 'add_dataitem':
src/dataitem_c.c:109:13: warning: assignment discards 'const' qualifier from pointer target type [enabled by default]
  head->next = addme;
             ^
src/system_c.c: In function 'unpack_system':
src/system_c.c:154:2: warning: implicit declaration of function 'ntohl' [-Wimplicit-function-declaration]
  size = ntohl( netOrder );
  ^
src/vpdretriever_c.c: In function 'build_component_sub':
src/vpdretriever_c.c:33:8: warning: unused variable 'id' [-Wunused-variable]
  char *id;
        ^
src/vpdretriever_c.c: In function 'build_system_sub':
src/vpdretriever_c.c:61:8: warning: unused variable 'id' [-Wunused-variable]
  char *id;

src/dataitem.cpp: In member function 'int lsvpd::DataItem::pack(void*)':
src/dataitem.cpp:225:7: warning: unused variable 'tmp' [-Wunused-variable]
   int tmp;
       ^
src/dataitem.cpp: In member function 'void lsvpd::DataItem::unpack(const void*)':
src/dataitem.cpp:260:7: warning: unused variable 'pos' [-Wunused-variable]
   int pos;

src/helper_functions.cpp: In static member function 'static char* lsvpd::HelperFunctions::fs_fixPath(char*)':
src/helper_functions.cpp:341:7: warning: unused variable 'i' [-Wunused-variable]
   int i;

src/helper_functions.cpp:263:8: warning: unused variable 'star' [-Wunused-variable]
   bool star = false;

src/helper_functions.cpp: In static member function 'static std::string lsvpd::HelperFunctions::getAbsolutePath(char*, char*)':
src/helper_functions.cpp:234:7: warning: variable 'lastHit' set but not used [-Wunused-but-set-variable]
   int lastHit;

Signed-Off-By: Janani Venkataraman <jananive@linux.vnet.ibm.com>
Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>
Acked-by: Suzuki K. Poulose <suzuki@in.ibm.com>